### ISSUE TITLE
Remove Time Zone Map

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-datetime#25]
With new settings it's getting kind of ridiculously tiny. This would automatically solve #6 and #8 

![screenshot from 2017-04-13 23 43 49](https://cloud.githubusercontent.com/assets/7277719/25035546/1453eb3c-20a3-11e7-8bc0-22d00a4ef873.png)

**Comment by torikulhabib** [comment]
how about this layout
![screenshot from 2018-10-11 07 36 29](https://user-images.githubusercontent.com/26135527/46775054-adedcd00-cd2f-11e8-8553-32686d3b64b8.png)
