### ISSUE TITLE
current master (c6304c4) fails to build due to botched translations

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-datetime#32]
During compilation, I get lots of errors similar to the following one (for different files at different lines):

```
.../po/ak.po:3055: duplicate message definition...
.../po/ak.po:53: ...this is the location of the first definition
(...)
/usr/bin/msgfmt: found 22 fatal errors
```

Did weblate mess up translations?

**Comment by btkostner** [comment]
Probably. Oddly enough it seems to be this repo mostly. I'll try recreating the project in weblate when I get a chance.

**Comment by danrabbit** [comment]
reverted back to the last known good commit and made pot and po. We'll see what happens on the next weblate merge :grimacing:

**Comment by decathorpe** [comment]
Thanks for looking into this. The last commit built successfully, let's hope it stays that way :+1:
