### ISSUE TITLE
Selected time format is not global

### ISSUE THREAD

**Issue by Sebzlol** [elementary/switchboard-plug-datetime#49]
If you select 24H time format it still shows AM/PM several places.

Examples are at the lock screen and in the calendar. Might be other places too.

**Comment by peteruithoven** [comment]
Thanks for the report! This is actually a duplicate of / related to:
- https://github.com/elementary/greeter/issues/52
- https://github.com/elementary/greeter/issues/171
- https://github.com/elementary/calendar/issues/268
