### ISSUE TITLE
Add option to sync current timezone from geolocation

### ISSUE THREAD

**Issue by jmc-88** [elementary/switchboard-plug-datetime#57]
Currently, elementary provides the option to sync the clock for the current timezone with network time. It would be nice to also have the option to sync the _current timezone itself_ through geolocation data -- Chrome OS currently does this and I find it to be a very convenient feature.

For geolocation, IP address is a good clue provided a VPN is not in use. This is exactly what [tzupdate](https://github.com/cdown/tzupdate) uses.

**Comment by danrabbit** [comment]
Closing as a duplicate of #3
