### ISSUE TITLE
Crashes without schema from wingpanel-indicator-datetime

### ISSUE THREAD

**Issue by codygarver** [elementary/switchboard-plug-datetime#64]
Date & Time plug crashes without `io.elementary.desktop.wingpanel.datetime`.

To reproduce the crash you can:
`sudo apt-get remove wingpanel-indicator-datetime`

Then you get this:
```
(io.elementary.switchboard:3360): GLib-GIO-ERROR **: 20:04:44.131: Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed
```

**Comment by danrabbit** [comment]
This appears to have been fixed
