### ISSUE TITLE
Does the new layout look better if its components are centered?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/switchboard-plug-datetime#69]
Thanks for the new layout of switchboard-plug-datetime!

That's how the design looks to me right now.
![Screenshot cleaned](https://user-images.githubusercontent.com/46536067/63082331-405d8f00-bf46-11e9-9153-a05739b0f2ce.png)

Do you think it would be better to center the components more?
An evaluation is difficult for me personally, because I have looked at the other plugins, and these look visually different.

**Comment by worldofpeace** [comment]
I believe this is what you're looking for #61

**Comment by 4jNsY6fCVqZv** [comment]
Hi, I'm afraid not. In your example it is even "worse", because the display "24h" even overlaps the "Search Settings" bar at the top. From my perception, the arrangement is right-justified rather than centered. And that's what I want to express with the issue here. Do you understand? My idea would be to arrange it in a direct line under "Time & Date".

**Comment by worldofpeace** [comment]
I didn't write the code, but I'm sure for https://github.com/elementary/switchboard-plug-datetime/pull/61 your suggestions would be welcome on how we can make it look better :+1:

**Comment by ryonakano** [comment]
![Screenshot from 2019-08-20 07-59-32](https://user-images.githubusercontent.com/26003928/63305293-40340980-c321-11e9-901b-538c7ff20f4f.png)

![Screenshot from 2019-08-20 08-03-23](https://user-images.githubusercontent.com/26003928/63305294-40340980-c321-11e9-8853-c5e45f68b28c.png)

Hmm, I think the layouts of both `master` and #61 is centered horizontally.

**Comment by worldofpeace** [comment]
Right, I'm assuming because of the now-defunct map it appeared centered as well. (though not actually)

**Comment by 4jNsY6fCVqZv** [comment]
I have switchboard-plug-datetime 2.1.6 running, unfortunately it looks like in my screenshot. So the master branch's fixing that?

**Comment by ryonakano** [comment]
@4jNsY6fCVqZv As far as [comparing the master and 2.1.6](https://github.com/elementary/switchboard-plug-datetime/compare/2.1.6...master), there are no code changes, so the layout is not changed at all.

**Comment by 4jNsY6fCVqZv** [comment]
@ryonakano Could it be that your screenshot was taken in maximized mode and mine in non-maximized mode? And does this distort the way it is displayed?

**Comment by ryonakano** [comment]
@4jNsY6fCVqZv Nope, both of ours ware taken in non-maximized mode. FYI the following one is taken in maximized mode, whose contents seems to be still centered.

![Screenshot from 2019-08-20 21-42-11](https://user-images.githubusercontent.com/26003928/63348082-8924a600-c393-11e9-9e76-54238b99310f.png)

**Comment by 4jNsY6fCVqZv** [comment]
Okay, figured out what it is. The problem from my point of view is that I can't reset a window size to default once I've resized it. And that leads to a situation where there is no centering for unmaximized windows, right?

**Comment by danirabbit** [comment]
Closing since the layout is now more centered/vertical and in a clamp :)
