### ISSUE TITLE
The time shown is wrong.

### ISSUE THREAD

**Issue by wijaya-hendra** [elementary/switchboard-plug-datetime#82]
Hi,
I use Elementary OS Hera and Windows 10 in the same PC (dual boot).
I got difficulties to set up the time.  Any setting gives the wrong result.
The Hera always shows 7 hours ahead.
I live in Indonesia (WIB time).
Please someone can help.
Thank you,
Hendra Wijaya

**Comment by ryonakano** [comment]
This is because how to handle time is different between *nix and Windows. Open your terminal and run the following command:

```
sudo timedatectl set-local-rtc 1
```

The issue should resolve once you reboot.
