### ISSUE TITLE
Timezone popover is tiny by default

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-datetime#86]
This might be due (in part) to not having a default timezone set or something, but in elementary OS 6 images I've noticed this:

![Screenshot from 2020-08-12 23-24-24](https://user-images.githubusercontent.com/611168/90078157-8123eb80-dcf3-11ea-9a39-705574459f70.png)

The left sidebar in the popover is not scrollable. If you can manage to select a timezone, it's still tiny vertically.

![Screenshot from 2020-08-12 17 29 26](https://user-images.githubusercontent.com/611168/90078234-baf4f200-dcf3-11ea-8a00-8a16057c5a02.png)

**Comment by meisenzahl** [comment]
This might was related with the issue described in https://github.com/elementary/applications-menu/issues/423

I am not able to reproduce this.

@cassidyjames can we close this?

**Comment by ryonakano** [comment]
Not him, but interestingly I'm also no longer able to reproduce this issue, while I do still see the one in the application menu :thinking:

![screenshot](https://user-images.githubusercontent.com/26003928/102322895-2103c580-3fc3-11eb-9b74-fa138578644f.png)

**Comment by AlexDerbenew** [comment]
Caught this bug today. Timezone was wrong, had to open datetime plug to change it but could not do anything due to size of popover

**Comment by cassidyjames** [comment]
Yeah, to clarify: this happens on a fresh install. In my experience, it is not reproducible once you select a timezone.

**Comment by cassidyjames** [comment]
fixed in #61
