### ISSUE TITLE
Switching between AM/PM and 24 hour clock changes dark theme

### ISSUE THREAD

**Issue by agoe1179** [elementary/switchboard-plug-datetime#88]
## What Happened
After switching to dark theme, I switched from the 24 hour time format to AM/PM. Doing so always results in the theme reverting back to the default light theme.

## Expected Behavior
Switching the time format should have no effect on the theme

## Steps to Reproduce

1. Switch elementary theme to dark mode
2. Switch the time format from AM/PM to 24 hour clock

## Platform Information
elementary os 6, latest release

**Comment by TKivai** [comment]
This is still an issue in the beta version. https://imgur.com/a/2YopqSi

**Comment by marco4mp** [comment]
Do you still have the problem? I try to reproduce the steps using elementary 7 and it doesn't happen.

**Comment by TKivai** [comment]
> Do you still have the problem? I try to reproduce the steps using elementary 7 and it doesn't happen.

No. The issue seemed to be fixed. I think this can be closed.
