### ISSUE TITLE
pi 400 Location Based Time Zone Does Not Work

### ISSUE THREAD

**Issue by SwiftLemon** [elementary/switchboard-plug-datetime#90]
## What Happened

With location services enabled and the option to set time zone "Based on your Location" is set to on. The time zone does not automatically update to location.

## Expected Behavior

Time zone should have been set automatically via location.

## Steps to Reproduce

1. Ensure location services are enabled
2. Date & Time system settings menu
3. Select "Based on your Location"

## Platform Information

Build: elementaryos-6.0-daily-rpi-20210212
Device: Raspberry Pi 400

**Comment by selwynorren** [comment]
I have the exact same issue, however I am running the latest daily build for Standard Desktop

**Comment by ryonakano** [comment]
Closing as duplicate of #96
